---
title: "Data_Cleaning_Yunyang"
author: "Yunyang Zhong"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)         # for graphing and data cleaning
library(tidymodels)        # for modeling
library(stacks)            # for stacking models
library(naniar)            # for analyzing missing values
library(vip)               # for variable importance plots
library(usemodels)         # for tidymodels suggestions
library(xgboost)           # for boosting - need to install, don't need to load
library(doParallel)        # for parallel processing
library(lubridate)         # for dates
library(moderndive)        # for King County housing data
library(patchwork)         # for combining plots nicely
library(rmarkdown)         # for paged tables
theme_set(theme_minimal()) # Lisa's favorite theme
```

# Data Cleaning and Wrangling

```{r}
pm2017 <- read_csv("2017pm25.csv")
pm2018 <- read_csv("2018pm25.csv")
pm2019 <- read_csv("2019pm25.csv")

pm25 <- rbind(pm2017, pm2018, pm2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_pm25 = mean(`Daily Mean PM2.5 Concentration`))
```

```{r}
co2017 <- read_csv("2017co.csv")
co2018 <- read_csv("2018co.csv")
co2019 <- read_csv("2019co.csv")

co <- rbind(co2017, co2018, co2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_co = mean(`Daily Max 8-hour CO Concentration`))
```

```{r}
pm2017 <- read_csv("2017pm10.csv")
pm2018 <- read_csv("2018pm10.csv")
pm2019 <- read_csv("2019pm10.csv")

pm10 <- rbind(pm2017, pm2018, pm2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_pm10 = mean(`Daily Mean PM10 Concentration`))
```

```{r}
no22017 <- read_csv("2017no2.csv")
no22018 <- read_csv("2018no2.csv")
no22019 <- read_csv("2019no2.csv")

no2 <- rbind(no22017, no22018, no22019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_no2 = mean(`Daily Max 1-hour NO2 Concentration`))
```

```{r}
so22017 <- read_csv("2017so2.csv")
so22018 <- read_csv("2018so2.csv")
so22019 <- read_csv("2019so2.csv")

so2 <- rbind(so22017, so22018, so22019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_so2 = mean(`Daily Max 1-hour SO2 Concentration`))
```

```{r}
pb2017 <- read_csv("2017pb.csv")
pb2018 <- read_csv("2018pb.csv")
pb2019 <- read_csv("2019pb.csv")

pb <- rbind(pb2017, pb2018, pb2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_pb = mean(`Daily Mean Pb Concentration`))
```

```{r}
ozone2017 <- read_csv("2017ozone.csv")
ozone2018 <- read_csv("2018ozone.csv")
ozone2019 <- read_csv("2019ozone.csv")

ozone <- rbind(ozone2017, ozone2018, ozone2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_ozone = mean(`Daily Max 8-hour Ozone Concentration`))
```

```{r}
pollutant2 <- left_join(ozone, pb, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant3 <- left_join(pm25, pollutant2, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant4 <- left_join(pollutant3, pm10, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant5 <- left_join(pollutant4, co, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant6 <- left_join(pollutant5, no2, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant7 <- left_join(pollutant6, so2, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
```

```{r}
data <- read_csv("data.csv")
```

```{r}
lm(cancer_incidence_rate ~ annual_mean_pb + annual_mean_co + annual_mean_no2 + annual_mean_so2 + annual_mean_ozone + annual_mean_pm25 + annual_mean_pm10, data = data)
```

```{r}
data %>% 
  ggplot(aes(x = cancer_incidence_rate)) +
  geom_density()

data %>% 
  ggplot(aes(x = asthma_er_avg)) +
  geom_density()

data %>% 
  ggplot(aes(x = asthma_deaths)) +
  geom_density()
```

```{r}
data %>% 
  drop_na()
```

# Lasso Model

```{r}
pollution <- read.csv("data_standardized.csv")
```

```{r}
pollution %>% 
  select(where(is.numeric)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free",
             nrow = 5)
```

```{r}
pollution_mod <- pollution %>%
  mutate(log_asthma = log(asthma_er_avg, base = 10)) %>% 
  select(-asthma_er_avg) %>% 
  mutate(across(where(is.character), as.factor)) %>% 
  add_n_miss() %>% 
  filter(n_miss_all == 0) %>% 
  select(-n_miss_all)

set.seed(456)
pollution_split <- initial_split(pollution_mod, prop = .75)
pollution_training <- training(pollution_split)
pollution_testing <- testing(pollution_split)
```

```{r}
pollution_recipe <- recipe(log_asthma ~ ., data = pollution_training) %>% 
  step_rm(County,
          Year,
          All.causes..total.,
          Alzheimer.s.disease,
          Malignant.neoplasms,
          Chronic.lower.respiratory.diseases,
          Diabetes.mellitus,
          Assault..homicide.,
          Diseases.of.heart,
          Essential.hypertension.and.hypertensive.renal.disease,
          Accidents..unintentional.injuries.,
          Chronic.liver.disease.and.cirrhosis,
          Nephritis..nephrotic.syndrome.and.nephrosis,
          Parkinson.s.disease,
          Influenza.and.pneumonia,
          Cerebrovascular.diseases,
          Intentional.self.harm..suicide.,
          FIPS,
          cancer_incidence_rate,
          asthma_deaths,
          Bladder_Surgery_Ct,
          Brain_Surgery_Ct,
          Breast_Surgery_Ct,
          Colon_Surgery_Ct,
          Esophagus_Surgery_Ct,
          Liver_Surgery_Ct,
          Lung_Surgery_Ct,
          Pancreas_Surgery_Ct,
          Prostate_Surgery_Ct,
          Rectum_Surgery_Ct,
          Stomach_Surgery_Ct) %>% 
  step_normalize(all_predictors(), 
                 -all_nominal()) %>% 
  step_dummy(all_nominal(), 
             -all_outcomes())
```

```{r}
pollution_recipe %>% 
  prep(pollution_training) %>%
  juice()
```

```{r}
pollution_lasso_mod <- 
  linear_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("regression")
```

```{r}
pollution_lasso_wf <- 
  workflow() %>% 
  add_recipe(pollution_recipe) %>% 
  add_model(pollution_lasso_mod)
```

```{r}
penalty_grid <- grid_regular(penalty(),
                             levels = 20)
penalty_grid 
```

```{r}
ctrl_grid <- control_stack_grid()

set.seed(456)
pollution_cv <- vfold_cv(pollution_training, v = 5)

pollution_lasso_tune <- 
  pollution_lasso_wf %>% 
  tune_grid(
    resamples = pollution_cv,
    grid = penalty_grid,
    control = ctrl_grid
    )

pollution_lasso_tune
```

```{r}
pollution_lasso_tune %>% 
  select(id, .metrics) %>% 
  unnest(.metrics) %>% 
  filter(.metric == "rmse")
```

```{r}
pollution_lasso_tune %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  ggplot(aes(x = penalty, y = mean)) +
  geom_point() +
  geom_line() +
  scale_x_log10(
   breaks = scales::trans_breaks("log10", function(x) 10^x),
   labels = scales::trans_format("log10",scales::math_format(10^.x))) +
  labs(x = "penalty", y = "rmse")
```

```{r}
pollution_lasso_tune %>% 
  show_best(metric = "rmse")
```

```{r}
best_param <- pollution_lasso_tune %>% 
  select_best(metric = "rmse")
best_param
```

```{r}
one_se_param <- pollution_lasso_tune %>% 
  select_by_one_std_err(metric = "rmse", desc(penalty))
one_se_param
```

```{r}
pollution_lasso_final_wf <- pollution_lasso_wf %>% 
  finalize_workflow(one_se_param)
pollution_lasso_final_wf
```

```{r}
pollution_lasso_final_mod <- pollution_lasso_final_wf %>% 
  fit(data = pollution_training)

pollution_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  tidy() 
```

```{r}
pollution_lasso_test <- pollution_lasso_final_wf %>% 
  last_fit(pollution_split)

# Metrics for model applied to test data
pollution_lasso_test %>% 
  collect_metrics()
```

# Xgboost model

```{r}
use_xgboost(log_asthma ~ ., data = pollution_training)
```

```{r}
boost_recipe <- 
  recipe(formula = log_asthma ~ ., data = pollution_training) %>% 
  step_rm(County,
          Year,
          All.causes..total.,
          Alzheimer.s.disease,
          Malignant.neoplasms,
          Chronic.lower.respiratory.diseases,
          Diabetes.mellitus,
          Assault..homicide.,
          Diseases.of.heart,
          Essential.hypertension.and.hypertensive.renal.disease,
          Accidents..unintentional.injuries.,
          Chronic.liver.disease.and.cirrhosis,
          Nephritis..nephrotic.syndrome.and.nephrosis,
          Parkinson.s.disease,
          Influenza.and.pneumonia,
          Cerebrovascular.diseases,
          Intentional.self.harm..suicide.,
          FIPS,
          cancer_incidence_rate,
          asthma_deaths,
          Bladder_Surgery_Ct,
          Brain_Surgery_Ct,
          Breast_Surgery_Ct,
          Colon_Surgery_Ct,
          Esophagus_Surgery_Ct,
          Liver_Surgery_Ct,
          Lung_Surgery_Ct,
          Pancreas_Surgery_Ct,
          Prostate_Surgery_Ct,
          Rectum_Surgery_Ct,
          Stomach_Surgery_Ct) %>% 
  step_novel(all_nominal_predictors()) %>% 
  step_dummy(all_nominal_predictors(), one_hot = TRUE)  %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors(), 
                 -all_nominal())
```

```{r}
boost_recipe %>% 
  prep() %>% 
  juice() 
```

```{r}
boost_spec <- boost_tree(
  trees = 1000,            # number of trees, T in the equations above
  tree_depth = 2,          # max number of splits in the tree
  min_n = 5,               # min points required for node to be further split
  loss_reduction = 10^-5,  # when to stop - smaller = more since it only has to get a little bit better 
  sample_size = 1,         # proportion of training data to use
  learn_rate = tune(),     # lambda from the equations above
  stop_iter = 50           # number of iterations w/o improvement b4 stopping
) %>% 
  set_engine("xgboost", colsample_bytree = 1) %>% 
  set_mode("regression")
```

```{r}
boost_grid <- grid_regular(learn_rate(),
                           levels = 10)
boost_grid
```

```{r}
boost_wf <- workflow() %>% 
  add_recipe(boost_recipe) %>%
  add_model(boost_spec) 
```

```{r}
set.seed(456)
val_split <- validation_split(pollution_training, 
                              prop = .6)
val_split
```

```{r}
set.seed(456)
registerDoParallel()

boost_tune <- boost_wf %>% 
  tune_grid(
  # resamples = val_split,
  resamples = pollution_cv,
  grid = boost_grid,
  control = ctrl_grid
)
```

```{r}
collect_metrics(boost_tune)
```

```{r}
collect_metrics(boost_tune) %>% 
  filter(.metric == "rmse") %>% 
  ggplot(aes(x = learn_rate, y = mean)) +
  geom_point() +
  geom_line() +
  scale_x_log10() +
  labs(y = "rmse") +
  theme_minimal()
```

```{r}
best_lr <- select_best(boost_tune, "rmse")
best_lr
```

```{r}
# finalize workflow
final_boost_wf <- finalize_workflow(
  boost_wf,
  best_lr
)

# fit final
final_boost <- final_boost_wf %>% 
  fit(data = pollution_training)
```

```{r}
final_boost %>% 
  pull_workflow_fit() %>%
  vip(geom = "col")
```

```{r}
# Use model on test data
test_preds <- pollution_testing %>% 
  bind_cols(predict(final_boost, new_data = pollution_testing)) 

# Compute test rmse
test_preds %>% 
  summarize(rmse = sqrt(mean((log_asthma - .pred)^2))) %>% 
  pull(rmse)
```

```{r}
# Graph results
test_preds %>% 
  ggplot(aes(x = log_asthma,
             y = .pred)) +
  geom_point(alpha = .5, 
             size = .5) +
  geom_smooth(se = FALSE) +
  geom_abline(slope = 1, 
              intercept = 0, 
              color = "darkred") +
  labs(x = "Actual log(asthma)", 
       y = "Predicted log(asthma)")
```

# Stacking

```{r}
pollution_stack <- 
  stacks() %>% 
  add_candidates(boost_tune) %>%
  add_candidates(pollution_lasso_tune)

as_tibble(pollution_stack)
```

```{r}
set.seed(456)

pollution_blend <- 
  pollution_stack %>% 
  blend_predictions()

pollution_blend
```

```{r}
pollution_blend$metrics %>% 
  filter(.metric == "rmse")
```

```{r}
autoplot(pollution_blend)
```

```{r}
autoplot(pollution_blend, type = "members")
```

```{r}
autoplot(pollution_blend, type = "weights")
```

```{r}
pollution_final_stack <- pollution_blend %>% 
  fit_members()

pollution_final_stack
```

```{r}
pollution_final_stack %>% 
  predict(new_data = pollution_testing) %>% 
  bind_cols(pollution_testing) %>% 
  ggplot(aes(x = log_asthma, 
             y = .pred)) +
  geom_point(alpha = .5, 
             size = .5) +
  geom_smooth(se = FALSE) +
  geom_abline(slope = 1, 
              intercept = 0, 
              color = "darkred") +
  labs(x = "Actual log(asthma)", 
       y = "Predicted log(asthma)")
```

