---
title: "Data Cleaning - Mia"
author: "Mia Rothberg"
date: "11/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```

```{r}
ca_pop <- read_csv("ca_county_est.csv") %>% 
  mutate(County = ifelse(County == "Humbolt", "Humboldt", County))
```

```{r}
ca_pop <- ca_pop %>% 
  pivot_longer(!County, names_to = "Year", values_to = "Population") %>% 
  mutate(Year = as.double(Year))
```

```{r}
#data source: https://catalog.data.gov/dataset/asthma-deaths-by-county
asthma_deaths_CA <- read_csv("asthma_deaths.csv")

#data source: https://catalog.data.gov/dataset/asthma-emergency-department-visit-rates 
asthma_emergency_visits <- read_csv("asthma-emergency-department-visit-rates-by-county-2015_2019.csv")

#https://statecancerprofiles.cancer.gov/incidencerates/index.php?stateFIPS=06&areatype=county&cancer=055&race=00&sex=2&age=001&stage=999&year=0&type=incd&sortVariableName=rate&sortOrder=default&output=0#results
#not reading in right but the file looks fine
cancer <- read_csv("breast_cancer_women_5yravg_updated.csv")
```

```{r}
asthma_deaths_CA_clean <- asthma_deaths_CA %>% 
  mutate(YEARS = ifelse(str_detect(YEARS, "2014"), "2014.2016", "2017.2019")) %>% 
  filter(YEARS == "2017.2019",
         `AGE GROUP` == "All ages")

cancer_clean <- cancer %>% 
  mutate(County = ifelse(str_detect(County, "(7)"), substr(County, 1, nchar(County) - 3), County)) %>% 
  mutate(County = substr(County, 1, nchar(County) - 7)) %>% 
  mutate(County = ifelse(County == "Cal", "California", County))

asthma_er_clean <- asthma_emergency_visits %>% 
  select(-COMMENT) %>% 
  filter(YEAR > 2016) %>% 
  filter(`AGE GROUP` == "All ages") %>%
  filter(STRATA == "Total population") %>% 
  na.omit() %>% 
  group_by(COUNTY) %>% 
  summarize(asthma_er_avg = mean(`NUMBER OF ED VISITS`))
 
```

```{r}
illness_data <- cancer_clean %>% 
  left_join(asthma_deaths_CA_clean, by = c("County" = "COUNTY")) %>% 
  left_join(asthma_er_clean, by = c("County" = "COUNTY")) %>% 
  mutate(cancer_incidence_rate = `Age-Adjusted Incidence Rate([rate note]) - cases per 100,000`,
         asthma_deaths = `NUMBER OF DEATHS`) %>% 
  mutate(cancer_incidence_rate = as.numeric(cancer_incidence_rate)) %>% 
  select(County, FIPS, asthma_er_avg, cancer_incidence_rate, asthma_deaths)
```

```{r}
pm2017 <- read_csv("2017pm25.csv")
pm2018 <- read_csv("2018pm25.csv")
pm2019 <- read_csv("2019pm25.csv")

#modified to only have one value per county
pm25 <- rbind(pm2017, pm2018, pm2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_pm25 = mean(`Daily Mean PM2.5 Concentration`))
```

```{r}
co2017 <- read_csv("2017co.csv")
co2018 <- read_csv("2018co.csv")
co2019 <- read_csv("2019co.csv")

co <- rbind(co2017, co2018, co2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_co = mean(`Daily Max 8-hour CO Concentration`))
```

```{r}
pm2017 <- read_csv("2017pm10.csv")
pm2018 <- read_csv("2018pm10.csv")
pm2019 <- read_csv("2019pm10.csv")

pm10 <- rbind(pm2017, pm2018, pm2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_pm10 = mean(`Daily Mean PM10 Concentration`))
```

```{r}
no22017 <- read_csv("2017no2.csv")
no22018 <- read_csv("2018no2.csv")
no22019 <- read_csv("2019no2.csv")

no2 <- rbind(no22017, no22018, no22019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_no2 = mean(`Daily Max 1-hour NO2 Concentration`))
```

```{r}
so22017 <- read_csv("2017so2.csv")
so22018 <- read_csv("2018so2.csv")
so22019 <- read_csv("2019so2.csv")

so2 <- rbind(so22017, so22018, so22019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_so2 = mean(`Daily Max 1-hour SO2 Concentration`))
```

```{r}
pb2017 <- read_csv("2017pb.csv")
pb2018 <- read_csv("2018pb.csv")
pb2019 <- read_csv("2019pb.csv")

pb <- rbind(pb2017, pb2018, pb2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_pb = mean(`Daily Mean Pb Concentration`))
```

```{r}
ozone2017 <- read_csv("2017ozone.csv")
ozone2018 <- read_csv("2018ozone.csv")
ozone2019 <- read_csv("2019ozone.csv")

ozone <- rbind(ozone2017, ozone2018, ozone2019) %>% 
  mutate(Year = substr(Date,nchar(Date)-3, nchar(Date))) %>% 
  group_by(COUNTY, Year) %>% 
  summarise(annual_mean_ozone = mean(`Daily Max 8-hour Ozone Concentration`))
```

```{r}
pollutant2 <- left_join(ozone, pb, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant3 <- left_join(pm25, pollutant2, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant4 <- left_join(pollutant3, pm10, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant5 <- left_join(pollutant4, co, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant6 <- left_join(pollutant5, no2, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
pollutant7 <- left_join(pollutant6, so2, by = c("Year" = "Year", "COUNTY" = "COUNTY"))
```

```{r}
data <- pollutant7 %>% 
  left_join(illness_data, by = c("COUNTY" = "County")) %>% 
  mutate(Year = as.double(Year))
```

```{r, eval=FALSE}
write.csv(data, "data.csv")
```

```{r}
data %>% 
  filter(!(COUNTY == "California")) %>% 
  ggplot(aes(x = annual_mean_pm25, y = asthma_er_avg)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Asthma ER visits")

data %>% 
  filter(!(COUNTY == "California")) %>% 
  filter(Year == 2017) %>% 
  ggplot(aes(x = annual_mean_ozone, y = asthma_er_avg)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Asthma and Ozone")

data %>% 
  filter(!(COUNTY == "California")) %>% 
  ggplot(aes(x = annual_mean_pm25, y = cancer_incidence_rate)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Cancer")
```


```{r}
california_deaths <- read_csv("2021-04-14_deaths_final_2014_2019_county_year_sup.csv")
```


```{r}
california_deaths_2017 <- california_deaths %>% 
  drop_na(Count) %>% 
  filter(Year > 2016,
         Strata_Name == "Total Population") %>% 
  group_by(County, Strata_Name, Cause, Cause_Desc, Year) %>% 
  summarize(deaths_per_year = mean(Count)) %>% 
  left_join(ca_pop, by = c("County", "Year")) %>% 
  mutate(deaths_pp = deaths_per_year/Population)
```


```{r}
california_deaths_all_years <- california_deaths_2017 %>% 
  ungroup() %>% 
  dplyr::select(County, Cause_Desc, deaths_pp, Year) %>% 
  pivot_wider(names_from = Cause_Desc, values_from = deaths_pp)
```

```{r}
#data source: https://data.ca.gov/dataset/number-of-cancer-surgeries-volume-performed-in-california-hospitals
cancer_hospitals <- read_csv("Cancer_in_CA_hospitals.csv")
```

```{r}
cancer_hospitals_clean <- cancer_hospitals %>% 
  left_join(ca_pop, by = c("County", "Year")) %>% 
  mutate(surgery_pp = `# of Cases (ICD 10)`/Population) %>% 
  select(Year, County, Hospital, Surgery, surgery_pp) %>% 
  mutate(Surgery = str_glue("{Surgery}_Surgery_Ct",
                            Surgery = Surgery)) %>% 
  filter(Year > 2016,
         Hospital != "Statewide") %>% 
  group_by(Year, County, Surgery) %>% 
  summarize(Surgery_Ct = sum(surgery_pp)) %>% 
  spread(key = Surgery, value = Surgery_Ct)

  cancer_hospitals_clean[is.na(cancer_hospitals_clean)] <- 0

```

```{r}
hpi <- read_csv("HPI2_MasterFile_2021-11-03.csv")
tree_canopy <- read_csv("HPI2_treecanopy.csv")
h2o_contam <- read_csv("HPI2_h20contam.csv")
park_access <- read_csv("HPI2_parkaccess.csv")
supermarkets <- read_csv("HPI2_supermkts.csv")

```

```{r}
hpi_county <- hpi %>% 
  group_by(County_Name) %>% 
  summarize(hpi2score = mean(na.omit(hpi2score)),
            economic = mean(na.omit(economic)),
            education = mean(na.omit(education)), 
            housing = mean(na.omit(housing)),
            healthcareaccess = mean(na.omit(healthcareaccess)),
            neighborhood = mean(na.omit(neighborhood)),
            pollution = mean(na.omit(pollution)),
            transportation = mean(na.omit(transportation)),
            social = mean(na.omit(social)),
            insured = mean(na.omit(insured)),
            uncrowded = mean(na.omit(uncrowded)),
            homeownership = mean(na.omit(homeownership)),
            automobile = mean(na.omit(automobile)),
            commute = mean(na.omit(commute)),
            inpreschool = mean(na.omit(inpreschool)),
            inhighschool = mean(na.omit(inhighschool)),
            bachelorsed = mean(na.omit(bachelorsed)),
            employed = mean(na.omit(employed)),
            abovepoverty = mean(na.omit(abovepoverty)),
            income = mean(na.omit(income))) 

#right now doing tree canopy average - would be better if we could weight the census tracts by area
tree_canopy <- tree_canopy %>% 
  group_by(County_Name) %>% 
  summarize(tree_canopy = mean(na.omit(treecanopy_pct)))

#percent of urban pop residing less than half a mile from a grocery store, rural pop less than 1 mile
supermarkets <- supermarkets %>% 
  group_by(County_Name) %>% 
  summarize(supermarkets = mean(na.omit(supermkts_pct)))

#percent of population living within 1/2 a mile of a park beach or open area greater than 1 acre
park_access <- park_access %>% 
  group_by(County_Name) %>% 
  summarize(park_access = mean(na.omit(parkaccess_pct)))

# CalEnviroScreen 3.0 drinking water contaminant index for selected contaminants
h2o_contam <- h2o_contam %>% 
  group_by(County_Name) %>% 
  summarize(h2o_contam = mean(na.omit(h20contam_pct)))

```

```{r}
hpi_county <- hpi_county %>% 
  left_join(tree_canopy, by = "County_Name") %>% 
  left_join(supermarkets, by = "County_Name") %>% 
  left_join(park_access, by = "County_Name") %>% 
  left_join(h2o_contam, by = "County_Name")
```


```{r}
data_deaths <- california_deaths_all_years %>% 
  #filter(Cause == "ALL") %>% 
  right_join(data, by = c("County" = "COUNTY", "Year" = "Year")) %>% 
  left_join(cancer_hospitals_clean, by = c("County" = "County", "Year" = "Year")) %>% 
  left_join(hpi_county, by = c("County" = "County_Name"))
```



```{r}
write_csv(data_deaths, "data_standardized.csv")
```


